-- GEAR-028: 헤드폰·이어폰 DAC/AMP 조합별 게인 설정 (headfi_device_settings)
--
-- ⚠️ 실행 전 백업을 권장합니다.
-- Supabase SQL Editor에서 수동 실행하세요. 에이전트가 직접 실행하지 않습니다.
--
-- 설계:
--   headfi_id    = 설정 대상 헤드폰/이어폰 (FK → headfi)
--   dac_amp_id   = 선택한 DAC/DAC·AMP/AMP (FK → headfi)
--   setting_text = 게인 등 자유 서술
--   user_id      = RLS용 (headfi_accessories 패턴)
--
-- 기존 headfi_device_settings 테이블이 있을 경우 아래 백업을 먼저 실행하세요:
-- CREATE TABLE headfi_device_settings_backup_gear028 AS SELECT * FROM headfi_device_settings;

CREATE TABLE IF NOT EXISTS public.headfi_device_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  headfi_id integer NOT NULL,
  dac_amp_id integer NOT NULL,
  setting_text text NOT NULL DEFAULT '',
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'headfi_device_settings_headfi_id_fkey'
  ) THEN
    ALTER TABLE public.headfi_device_settings
      ADD CONSTRAINT headfi_device_settings_headfi_id_fkey
      FOREIGN KEY (headfi_id) REFERENCES public.headfi (id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'headfi_device_settings_dac_amp_id_fkey'
  ) THEN
    ALTER TABLE public.headfi_device_settings
      ADD CONSTRAINT headfi_device_settings_dac_amp_id_fkey
      FOREIGN KEY (dac_amp_id) REFERENCES public.headfi (id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS headfi_device_settings_headfi_id_idx
  ON public.headfi_device_settings (headfi_id);

CREATE INDEX IF NOT EXISTS headfi_device_settings_user_id_idx
  ON public.headfi_device_settings (user_id);

COMMENT ON TABLE public.headfi_device_settings IS
  '헤드폰·이어폰별 DAC/AMP 조합 게인 등 설정 — GEAR-028';

COMMENT ON COLUMN public.headfi_device_settings.headfi_id IS
  '설정 대상 헤드폰/이어폰 FK';

COMMENT ON COLUMN public.headfi_device_settings.dac_amp_id IS
  '선택한 DAC/DAC·AMP/AMP FK';

COMMENT ON COLUMN public.headfi_device_settings.setting_text IS
  '게인 등 설정 정보(자유 서술)';

ALTER TABLE public.headfi_device_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "headfi_device_settings_select_own" ON public.headfi_device_settings;
CREATE POLICY "headfi_device_settings_select_own"
ON public.headfi_device_settings
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "headfi_device_settings_insert_own" ON public.headfi_device_settings;
CREATE POLICY "headfi_device_settings_insert_own"
ON public.headfi_device_settings
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "headfi_device_settings_update_own" ON public.headfi_device_settings;
CREATE POLICY "headfi_device_settings_update_own"
ON public.headfi_device_settings
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "headfi_device_settings_delete_own" ON public.headfi_device_settings;
CREATE POLICY "headfi_device_settings_delete_own"
ON public.headfi_device_settings
FOR DELETE
USING (auth.uid() = user_id);
